### PR TITLE
Add support for Laravel 8

### PR DESCRIPTION
**Pull request by cyrillkalita**
- Upgrade dependencies
- Remove version call-out in readme
- Remove extra spaces at the end of lines

### CODE REVIEW

**Comment by xevsy** [comment]
any updates? when can be merged?

**Comment by ishigami** [comment]
First of all, thanks to @alexpechkarev for this great package  👏  👏  👏. And @cyrillkalita for update the support for Laravel 8  👏  👏  👏. 

I will look forward to the update.  😳

Thanks again.

**Comment by PheRum** [comment]
merge please

**Comment by alexpechkarev** [comment]
Many tanks @cyrillkalita !

**Pull request merged**
