### PR TITLE
fix multiple requests

### PR DESCRIPTION
**Pull request by islamw**

### CODE REVIEW

**Comment by alexpechkarev** [comment]
Thank islamw !

**Comment by islamw** [comment]
Can you add google-maps to release? Because when i try composer update, i
have the same version

2016-01-29 1:18 GMT+02:00 Alexander Pechkarev <notifications@github.com>:

**Comment by islamw** [comment]
Can you do it right now?

**Comment by alexpechkarev** [comment]
Have added to the release "1.0.3"

**Comment by alexpechkarev** [comment]
Ok, it's now "1.0.4", packagist https://packagist.org/packages/alexpechkarev/google-maps

**Comment by islamw** [comment]
Alexander, thanks!

2016-01-29 14:40 GMT+02:00 Alexander Pechkarev <notifications@github.com>:

**Pull request merged**
